/**
 * Mock data — Seção CRM
 * Dinamic Imobiliária / Arapongas-PR
 *
 * Squad B (CRM): só LÊ tipos de @/lib/mock-types.
 * Tudo fictício mas realista (bairros reais de Arapongas-PR, nomes BR).
 */

import type { Lead, LeadStatus, Property } from "@/lib/mock-types";

// ============================================================
// Helpers
// ============================================================
const avatar = (n: number) => `https://i.pravatar.cc/150?img=${n}`;
const u = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=800&q=80&auto=format&fit=crop`;

// ============================================================
// KANBAN_LEADS — agrupados pelos 5 status do funil
// novo (4) · contatado (4) · qualificado (5) · visita (4) · proposta (3)
// 20 leads totais
// ============================================================
export const KANBAN_LEADS: Record<LeadStatus, Lead[]> = {
  novo: [
    {
      id: "ld-001",
      nome: "Mariana Silva",
      avatarUrl: avatar(1),
      bairro: "Centro",
      orcamento: 2800,
      intencao: "aluguel",
      status: "novo",
      setor: "locacao",
      ultimaInteracao: "agora",
    },
    {
      id: "ld-002",
      nome: "João Pereira",
      avatarUrl: avatar(12),
      bairro: "Jardim Tropical",
      orcamento: 420000,
      intencao: "compra",
      status: "novo",
      setor: "vendas",
      ultimaInteracao: "5 min",
    },
    {
      id: "ld-003",
      nome: "Carla Andrade",
      avatarUrl: avatar(5),
      bairro: "Jardim Universitário",
      orcamento: 1950,
      intencao: "aluguel",
      status: "novo",
      setor: "locacao",
      ultimaInteracao: "23 min",
    },
    {
      id: "ld-004",
      nome: "Roberto Lima",
      avatarUrl: avatar(15),
      bairro: "Industrial",
      orcamento: 580000,
      intencao: "compra",
      status: "novo",
      setor: "vendas",
      ultimaInteracao: "1h",
    },
  ],
  contatado: [
    {
      id: "ld-005",
      nome: "Ana Costa",
      avatarUrl: avatar(9),
      bairro: "Vale do Sol",
      orcamento: 1750,
      intencao: "aluguel",
      status: "contatado",
      setor: "locacao",
      ultimaInteracao: "2h",
    },
    {
      id: "ld-006",
      nome: "Pedro Souza",
      avatarUrl: avatar(33),
      bairro: "Aeroporto",
      orcamento: 350000,
      intencao: "compra",
      status: "contatado",
      setor: "vendas",
      ultimaInteracao: "3h",
    },
    {
      id: "ld-007",
      nome: "Fernanda Oliveira",
      avatarUrl: avatar(20),
      bairro: "Jardim Bandeirantes",
      orcamento: 2300,
      intencao: "aluguel",
      status: "contatado",
      setor: "locacao",
      ultimaInteracao: "5h",
    },
    {
      id: "ld-008",
      nome: "Lucas Ferreira",
      avatarUrl: avatar(52),
      bairro: "Centro",
      orcamento: 3400,
      intencao: "aluguel",
      status: "contatado",
      setor: "locacao",
      ultimaInteracao: "ontem",
    },
  ],
  qualificado: [
    {
      id: "ld-009",
      nome: "Beatriz Souza",
      avatarUrl: avatar(25),
      bairro: "Jardim Tropical",
      orcamento: 480000,
      intencao: "compra",
      status: "qualificado",
      setor: "vendas",
      ultimaInteracao: "ontem",
    },
    {
      id: "ld-010",
      nome: "Diego Martins",
      avatarUrl: avatar(13),
      bairro: "Vila Industrial",
      orcamento: 2200,
      intencao: "aluguel",
      status: "qualificado",
      setor: "locacao",
      ultimaInteracao: "ontem",
    },
    {
      id: "ld-011",
      nome: "Camila Rocha",
      avatarUrl: avatar(45),
      bairro: "Jardim Universitário",
      orcamento: 320000,
      intencao: "compra",
      status: "qualificado",
      setor: "vendas",
      ultimaInteracao: "ontem",
    },
    {
      id: "ld-012",
      nome: "Felipe Almeida",
      avatarUrl: avatar(68),
      bairro: "Centro",
      orcamento: 3200,
      intencao: "aluguel",
      status: "qualificado",
      setor: "locacao",
      ultimaInteracao: "anteontem",
    },
    {
      id: "ld-013",
      nome: "Juliana Mendes",
      avatarUrl: avatar(36),
      bairro: "Aeroporto",
      orcamento: 290000,
      intencao: "compra",
      status: "qualificado",
      setor: "captacao",
      ultimaInteracao: "anteontem",
    },
  ],
  visita: [
    {
      id: "ld-014",
      nome: "Gustavo Ferreira",
      avatarUrl: avatar(53),
      bairro: "Jardim Bandeirantes",
      orcamento: 690000,
      intencao: "compra",
      status: "visita",
      setor: "vendas",
      ultimaInteracao: "anteontem",
    },
    {
      id: "ld-015",
      nome: "Renata Pinto",
      avatarUrl: avatar(47),
      bairro: "Vale do Sol",
      orcamento: 2950,
      intencao: "aluguel",
      status: "visita",
      setor: "locacao",
      ultimaInteracao: "anteontem",
    },
    {
      id: "ld-016",
      nome: "Marcelo Dias",
      avatarUrl: avatar(60),
      bairro: "Industrial",
      orcamento: 4200,
      intencao: "aluguel",
      status: "visita",
      setor: "locacao",
      ultimaInteracao: "3 dias",
    },
    {
      id: "ld-017",
      nome: "Patrícia Ramos",
      avatarUrl: avatar(44),
      bairro: "Centro",
      orcamento: 520000,
      intencao: "compra",
      status: "visita",
      setor: "vendas",
      ultimaInteracao: "3 dias",
    },
  ],
  proposta: [
    {
      id: "ld-018",
      nome: "Vinícius Castro",
      avatarUrl: avatar(11),
      bairro: "Jardim Tropical",
      orcamento: 750000,
      intencao: "compra",
      status: "proposta",
      setor: "vendas",
      ultimaInteracao: "4 dias",
    },
    {
      id: "ld-019",
      nome: "Larissa Moura",
      avatarUrl: avatar(38),
      bairro: "Vila Industrial",
      orcamento: 3500,
      intencao: "aluguel",
      status: "proposta",
      setor: "locacao",
      ultimaInteracao: "5 dias",
    },
    {
      id: "ld-020",
      nome: "Bruno Carvalho",
      avatarUrl: avatar(57),
      bairro: "Jardim Universitário",
      orcamento: 410000,
      intencao: "compra",
      status: "proposta",
      setor: "vendas",
      ultimaInteracao: "6 dias",
    },
  ],
  fechado: [
    {
      id: "ld-021",
      nome: "Camila Ribeiro",
      avatarUrl: avatar(28),
      bairro: "Jardim Tropical",
      orcamento: 620000,
      intencao: "compra",
      status: "fechado",
      setor: "vendas",
      ultimaInteracao: "ontem",
    },
    {
      id: "ld-022",
      nome: "Eduardo Pinto",
      avatarUrl: avatar(64),
      bairro: "Centro",
      orcamento: 2400,
      intencao: "aluguel",
      status: "fechado",
      setor: "locacao",
      ultimaInteracao: "2 dias",
    },
    {
      id: "ld-023",
      nome: "Sandra Lima",
      avatarUrl: avatar(31),
      bairro: "Aeroporto",
      orcamento: 380000,
      intencao: "compra",
      status: "fechado",
      setor: "vendas",
      ultimaInteracao: "4 dias",
    },
  ],
  perdido: [
    {
      id: "ld-024",
      nome: "Márcio Costa",
      avatarUrl: avatar(42),
      bairro: "Jardim Bandeirantes",
      orcamento: 850000,
      intencao: "compra",
      status: "perdido",
      setor: "vendas",
      ultimaInteracao: "1 semana",
    },
    {
      id: "ld-025",
      nome: "Helena Reis",
      avatarUrl: avatar(19),
      bairro: "Vale do Sol",
      orcamento: 2100,
      intencao: "aluguel",
      status: "perdido",
      setor: "locacao",
      ultimaInteracao: "2 semanas",
    },
    {
      id: "ld-026",
      nome: "Antônio Silva",
      avatarUrl: avatar(50),
      bairro: "Industrial",
      orcamento: 470000,
      intencao: "compra",
      status: "perdido",
      setor: "vendas",
      ultimaInteracao: "3 semanas",
    },
  ],
};

// ============================================================
// 12 imóveis — catálogo demo Dinamic
// Mix: apto (6) · casa (3) · terreno (1) · comercial (2)
// Finalidade: venda (7) · aluguel (5) · 4 destaques
// ============================================================
export const PROPERTIES: Property[] = [
  {
    id: "im-001",
    titulo: "Apartamento 3 dorm Centro c/ sacada gourmet",
    bairro: "Centro",
    tipo: "apartamento",
    finalidade: "venda",
    preco: 485000,
    area: 78,
    dormitorios: 3,
    banheiros: 2,
    vagas: 2,
    fotos: [u("1522708323590-d24dbb6b0267")],
    destaque: true,
    endereco: "R. das Acácias, 420",
  },
  {
    id: "im-002",
    titulo: "Casa 4 dorm Jd Tropical c/ piscina",
    bairro: "Jardim Tropical",
    tipo: "casa",
    finalidade: "venda",
    preco: 720000,
    area: 180,
    dormitorios: 4,
    banheiros: 3,
    vagas: 2,
    fotos: [u("1568605114967-8130f3a36994")],
    destaque: true,
    endereco: "R. Tucano, 88",
  },
  {
    id: "im-003",
    titulo: "Apartamento 2 dorm mobiliado",
    bairro: "Jardim Universitário",
    tipo: "apartamento",
    finalidade: "aluguel",
    preco: 1850,
    area: 52,
    dormitorios: 2,
    banheiros: 1,
    vagas: 1,
    fotos: [u("1493809842364-78817add7ffb")],
    endereco: "Av. Universitária, 1.230",
  },
  {
    id: "im-004",
    titulo: "Apartamento 3 dorm reformado, andar alto",
    bairro: "Centro",
    tipo: "apartamento",
    finalidade: "aluguel",
    preco: 2650,
    area: 85,
    dormitorios: 3,
    banheiros: 2,
    vagas: 2,
    fotos: [u("1556909114-f6e7ad7d3136")],
    endereco: "R. Maranhão, 510",
  },
  {
    id: "im-005",
    titulo: "Casa 4 dorm moderna em condomínio",
    bairro: "Jardim Bandeirantes",
    tipo: "casa",
    finalidade: "venda",
    preco: 845000,
    area: 220,
    dormitorios: 4,
    banheiros: 3,
    vagas: 3,
    fotos: [u("1600585154340-be6161a56a0c")],
    destaque: true,
    endereco: "Cond. Vista Verde, 12",
  },
  {
    id: "im-006",
    titulo: "Apartamento 2 dorm c/ varanda",
    bairro: "Vale do Sol",
    tipo: "apartamento",
    finalidade: "aluguel",
    preco: 1650,
    area: 58,
    dormitorios: 2,
    banheiros: 1,
    vagas: 1,
    fotos: [u("1502672260266-1c1ef2d93688")],
    endereco: "R. Sabiá, 75",
  },
  {
    id: "im-007",
    titulo: "Apartamento 3 dorm cobertura duplex",
    bairro: "Aeroporto",
    tipo: "apartamento",
    finalidade: "venda",
    preco: 690000,
    area: 142,
    dormitorios: 3,
    banheiros: 3,
    vagas: 2,
    fotos: [u("1560448204-e02f11c3d0e2")],
    destaque: true,
    endereco: "Av. Aviadores, 980",
  },
  {
    id: "im-008",
    titulo: "Casa 3 dorm c/ edícula e quintal grande",
    bairro: "Vila Industrial",
    tipo: "casa",
    finalidade: "venda",
    preco: 540000,
    area: 200,
    dormitorios: 3,
    banheiros: 2,
    vagas: 4,
    fotos: [u("1605276374104-dee2a0ed3cd6")],
    endereco: "R. das Hortênsias, 33",
  },
  {
    id: "im-009",
    titulo: "Sala comercial pronta Centro",
    bairro: "Centro",
    tipo: "comercial",
    finalidade: "aluguel",
    preco: 4000,
    area: 110,
    dormitorios: 0,
    banheiros: 2,
    vagas: 2,
    fotos: [u("1497366216548-37526070297c")],
    endereco: "Av. Arapongas, 1.450",
  },
  {
    id: "im-010",
    titulo: "Apartamento 3 dorm alto padrão",
    bairro: "Jardim Tropical",
    tipo: "apartamento",
    finalidade: "venda",
    preco: 670000,
    area: 128,
    dormitorios: 3,
    banheiros: 3,
    vagas: 2,
    fotos: [u("1505693416388-ac5ce068fe85")],
    endereco: "R. Beija-Flor, 215",
  },
  {
    id: "im-011",
    titulo: "Terreno 360m² plano e escriturado",
    bairro: "Jardim Universitário",
    tipo: "terreno",
    finalidade: "venda",
    preco: 245000,
    area: 360,
    dormitorios: 0,
    banheiros: 0,
    vagas: 0,
    fotos: [u("1551522435-a13afa10f103")],
    endereco: "Lote 14, Quadra 8",
  },
  {
    id: "im-012",
    titulo: "Loja de esquina movimentada",
    bairro: "Industrial",
    tipo: "comercial",
    finalidade: "aluguel",
    preco: 3200,
    area: 95,
    dormitorios: 0,
    banheiros: 1,
    vagas: 1,
    fotos: [u("1564013799919-ab600027ffc6")],
    endereco: "Av. das Indústrias, 2.100",
  },
  {
    id: "im-013",
    titulo: "Casa 3 dorm com quintal — pet friendly",
    bairro: "Jardim Tropical",
    tipo: "casa",
    finalidade: "aluguel",
    preco: 2400,
    area: 110,
    dormitorios: 3,
    banheiros: 2,
    vagas: 2,
    fotos: [u("1605276374104-dee2a0ed3cd6")],
    destaque: true,
    endereco: "Rua das Magnólias, 245",
  },
  {
    id: "im-014",
    titulo: "Casa 2 dorm próxima ao Centro",
    bairro: "Centro",
    tipo: "casa",
    finalidade: "aluguel",
    preco: 1950,
    area: 85,
    dormitorios: 2,
    banheiros: 1,
    vagas: 1,
    fotos: [u("1568605114967-8130f3a36994")],
    endereco: "Rua dos Pioneiros, 588",
  },
  {
    id: "im-015",
    titulo: "Casa 4 dorm com edícula e churrasqueira",
    bairro: "Vale do Sol",
    tipo: "casa",
    finalidade: "aluguel",
    preco: 2950,
    area: 160,
    dormitorios: 4,
    banheiros: 3,
    vagas: 2,
    fotos: [u("1564013799919-ab600027ffc6")],
    endereco: "Rua Vale do Sol, 1020",
  },
];

// Helper retrocompatível (caso outros arquivos esperem CRM_LEADS / CRM_PROPERTIES)
export const CRM_LEADS: Lead[] = [
  ...KANBAN_LEADS.novo,
  ...KANBAN_LEADS.contatado,
  ...KANBAN_LEADS.qualificado,
  ...KANBAN_LEADS.visita,
  ...KANBAN_LEADS.proposta,
];
export const CRM_PROPERTIES = PROPERTIES;
