/**
 * Seed inicial do Task Manager — distribui ~30 tasks entre todos os setores
 * e colunas do kanban. Inclui tasks linkadas a contratos, boletos, leads e
 * LGPD requests pra mostrar o lado "tudo está conectado".
 */

import type { Task } from "@/lib/mock-types";

const today = "2026-05-22";
const todayISO = `${today}T08:00:00-03:00`;
const yesterdayISO = "2026-05-21T16:30:00-03:00";
const dayBefore = "2026-05-20T10:15:00-03:00";
const earlier = "2026-05-18T09:00:00-03:00";

export const TAREFAS_SEED: Task[] = [
  // ============== JURÍDICO ==============
  {
    id: "tsk-jur-001",
    titulo: "Revisar contrato locação — Rafael Mendes",
    descricao: "Locação Apto 2 dorm Jd Tropical. Conferir cláusula 8 (multa rescisória) e validar com locador.",
    status: "em_andamento",
    prioridade: "alta",
    setor: "juridico",
    responsavelNome: "Dra. Patrícia Soares",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=47",
    prazo: "2026-05-23",
    criadaEm: yesterdayISO,
    atualizadaEm: todayISO,
    labels: ["contrato_revisar"],
    linkedTo: { tipo: "contrato", id: "ct-2024-018", titulo: "Locação Apto Jd Tropical" },
    origem: "evento_sistema",
  },
  {
    id: "tsk-jur-002",
    titulo: "Recolher assinatura — Camila Ribeiro",
    descricao: "Compra Casa Centro R$ 485.000. Assinatura digital D4Sign pendente há 3 dias.",
    status: "aguardando_terceiros",
    prioridade: "urgente",
    setor: "juridico",
    responsavelNome: "Dra. Patrícia Soares",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=47",
    prazo: "2026-05-22",
    criadaEm: dayBefore,
    atualizadaEm: yesterdayISO,
    labels: ["recolher_assinatura", "aguardando_documento"],
    linkedTo: { tipo: "contrato", id: "ct-2024-022", titulo: "Compra Casa Centro" },
    origem: "evento_sistema",
  },
  {
    id: "tsk-jur-003",
    titulo: "Processar solicitação LGPD — Export dados",
    descricao: "Titular: Marina Almeida (CPF ***.789.***-**). Prazo legal: 15 dias.",
    status: "a_fazer",
    prioridade: "alta",
    setor: "juridico",
    responsavelNome: "Bruno Tavares",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=12",
    prazo: "2026-05-30",
    criadaEm: yesterdayISO,
    atualizadaEm: yesterdayISO,
    labels: ["lgpd_processar"],
    linkedTo: { tipo: "lgpd_request", id: "lgpd-2026-014", titulo: "Export — Marina Almeida" },
    origem: "evento_sistema",
  },
  {
    id: "tsk-jur-004",
    titulo: "Renovação contrato — Eduardo Pinto",
    descricao: "Contrato vence em 28 dias. Propor renovação + reajuste IGPM.",
    status: "em_revisao",
    prioridade: "normal",
    setor: "juridico",
    responsavelNome: "Dra. Patrícia Soares",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=47",
    prazo: "2026-06-15",
    criadaEm: earlier,
    atualizadaEm: dayBefore,
    labels: ["renovacao", "contrato_revisar"],
    linkedTo: { tipo: "contrato", id: "ct-2023-091", titulo: "Locação Industrial — E. Pinto" },
    origem: "evento_sistema",
  },
  {
    id: "tsk-jur-005",
    titulo: "Minutar termo aditivo — Sandra Lima",
    status: "a_fazer",
    prioridade: "normal",
    setor: "juridico",
    responsavelNome: "Bruno Tavares",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=12",
    prazo: "2026-05-26",
    criadaEm: yesterdayISO,
    atualizadaEm: yesterdayISO,
    labels: ["contrato_revisar"],
    linkedTo: { tipo: "contrato", id: "ct-2024-025", titulo: "Aditivo Aluguel Centro" },
    origem: "manual",
  },

  // ============== FINANCEIRO ==============
  {
    id: "tsk-fin-001",
    titulo: "Emitir boleto entrada — Camila Ribeiro",
    descricao: "Compra Casa Centro. Sinal de R$ 48.500 (10%).",
    status: "a_fazer",
    prioridade: "urgente",
    setor: "financeiro",
    responsavelNome: "Marcelo Vieira",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=33",
    prazo: "2026-05-22",
    criadaEm: yesterdayISO,
    atualizadaEm: yesterdayISO,
    labels: ["boleto_emitir"],
    linkedTo: { tipo: "boleto", id: "blt-2026-148", titulo: "Sinal — Camila Ribeiro" },
    origem: "evento_sistema",
  },
  {
    id: "tsk-fin-002",
    titulo: "Cobrança boleto vencido — Helena Reis",
    descricao: "Aluguel maio R$ 1.850. Vencido há 8 dias. Última tentativa: WhatsApp ontem.",
    status: "em_andamento",
    prioridade: "alta",
    setor: "financeiro",
    responsavelNome: "Marcelo Vieira",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=33",
    prazo: "2026-05-24",
    criadaEm: earlier,
    atualizadaEm: todayISO,
    labels: ["follow_up_lead"],
    linkedTo: { tipo: "boleto", id: "blt-2026-112", titulo: "Aluguel Maio — H. Reis" },
    origem: "evento_sistema",
  },
  {
    id: "tsk-fin-003",
    titulo: "Repasse mensal — Locador José Andrade",
    descricao: "5 imóveis. Total R$ 9.420 (já descontada comissão).",
    status: "aguardando_terceiros",
    prioridade: "normal",
    setor: "financeiro",
    responsavelNome: "Luciana Borges",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=49",
    prazo: "2026-05-25",
    criadaEm: dayBefore,
    atualizadaEm: yesterdayISO,
    labels: ["aguardando_documento"],
    origem: "manual",
  },
  {
    id: "tsk-fin-004",
    titulo: "Pagar comissão — Carlos Brito (abril)",
    descricao: "4 fechamentos · VGV R$ 1.2M · comissão R$ 28.450",
    status: "em_revisao",
    prioridade: "normal",
    setor: "financeiro",
    responsavelNome: "Luciana Borges",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=49",
    prazo: "2026-05-28",
    criadaEm: earlier,
    atualizadaEm: dayBefore,
    labels: ["comissao_pagar"],
    origem: "evento_sistema",
  },
  {
    id: "tsk-fin-005",
    titulo: "Conciliação bancária — Bradesco maio",
    status: "a_fazer",
    prioridade: "baixa",
    setor: "financeiro",
    responsavelNome: "Marcelo Vieira",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=33",
    prazo: "2026-05-31",
    criadaEm: yesterdayISO,
    atualizadaEm: yesterdayISO,
    labels: [],
    origem: "manual",
  },
  {
    id: "tsk-fin-006",
    titulo: "Negociação acordo — Antônio Silva",
    descricao: "Boletos abril+maio em aberto (R$ 4.620). Cliente propôs parcelar 3x.",
    status: "bloqueada",
    prioridade: "alta",
    setor: "financeiro",
    responsavelNome: "Luciana Borges",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=49",
    criadaEm: earlier,
    atualizadaEm: dayBefore,
    labels: ["follow_up_lead"],
    linkedTo: { tipo: "boleto", id: "blt-2026-088", titulo: "Aluguel abril/maio — A. Silva" },
    origem: "evento_sistema",
    bloqueadaPor: "Aguardando aval do gestor",
  },

  // ============== CAPTAÇÃO ==============
  {
    id: "tsk-cap-001",
    titulo: "Confirmar visita Apto Centro — Rodrigo Santos",
    descricao: "Visita marcada pela IA pra quinta 14h. Confirmar com corretor.",
    status: "a_fazer",
    prioridade: "alta",
    setor: "captacao",
    responsavelNome: "Fernanda Pires",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=44",
    prazo: "2026-05-23",
    criadaEm: yesterdayISO,
    atualizadaEm: yesterdayISO,
    labels: ["visita_confirmar"],
    linkedTo: { tipo: "lead", id: "ld-ai-001", titulo: "Rodrigo Santos" },
    origem: "ia",
  },
  {
    id: "tsk-cap-002",
    titulo: "Agendar vistoria — Casa Jardim Industrial",
    status: "em_andamento",
    prioridade: "normal",
    setor: "captacao",
    responsavelNome: "Fernanda Pires",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=44",
    prazo: "2026-05-26",
    criadaEm: dayBefore,
    atualizadaEm: todayISO,
    labels: ["vistoria_agendar"],
    linkedTo: { tipo: "imovel", id: "imv-088", titulo: "Casa Jd Industrial" },
    origem: "manual",
  },
  {
    id: "tsk-cap-003",
    titulo: "Atualizar fotos Apto 3 dorm Centro",
    descricao: "Anúncio com fotos de 2024. Reagendar sessão de fotos.",
    status: "a_fazer",
    prioridade: "baixa",
    setor: "captacao",
    responsavelNome: "Fernanda Pires",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=44",
    prazo: "2026-06-05",
    criadaEm: earlier,
    atualizadaEm: earlier,
    labels: [],
    linkedTo: { tipo: "imovel", id: "imv-042", titulo: "Apto Centro 3 dorm" },
    origem: "manual",
  },

  // ============== VENDAS ==============
  {
    id: "tsk-ven-001",
    titulo: "Follow-up proposta — Mariana Costa",
    descricao: "Proposta enviada há 4 dias (R$ 410k vs R$ 425k pedido). Sem resposta.",
    status: "em_andamento",
    prioridade: "alta",
    setor: "vendas",
    responsavelNome: "Carlos Brito",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=15",
    prazo: "2026-05-23",
    criadaEm: dayBefore,
    atualizadaEm: yesterdayISO,
    labels: ["follow_up_lead"],
    linkedTo: { tipo: "lead", id: "ld-009", titulo: "Mariana Costa" },
    origem: "evento_sistema",
  },
  {
    id: "tsk-ven-002",
    titulo: "Reabordar lead perdido — Márcio Costa",
    descricao: "Lead frio há 3 semanas. Imóveis novos na faixa de orçamento.",
    status: "a_fazer",
    prioridade: "normal",
    setor: "vendas",
    responsavelNome: "Carlos Brito",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=15",
    prazo: "2026-05-27",
    criadaEm: yesterdayISO,
    atualizadaEm: yesterdayISO,
    labels: ["follow_up_lead"],
    linkedTo: { tipo: "lead", id: "ld-perdido-001", titulo: "Márcio Costa" },
    origem: "manual",
  },
  {
    id: "tsk-ven-003",
    titulo: "Apresentar contraproposta — Eduardo Pinto",
    status: "em_revisao",
    prioridade: "alta",
    setor: "vendas",
    responsavelNome: "Ana Lima",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=20",
    prazo: "2026-05-22",
    criadaEm: yesterdayISO,
    atualizadaEm: todayISO,
    labels: [],
    linkedTo: { tipo: "lead", id: "ld-fechado-002", titulo: "Eduardo Pinto" },
    origem: "evento_sistema",
  },
  {
    id: "tsk-ven-004",
    titulo: "Comemorar fechamento — Camila Ribeiro",
    descricao: "Contrato assinado ontem. Mandar kit boas-vindas + agendar mudança.",
    status: "concluida",
    prioridade: "normal",
    setor: "vendas",
    responsavelNome: "Ana Lima",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=20",
    criadaEm: dayBefore,
    atualizadaEm: yesterdayISO,
    labels: [],
    linkedTo: { tipo: "lead", id: "ld-fechado-001", titulo: "Camila Ribeiro" },
    origem: "evento_sistema",
  },

  // ============== LOCAÇÃO ==============
  {
    id: "tsk-loc-001",
    titulo: "Aprovar fiador — Visita Bruno Carvalho",
    descricao: "Documentos enviados. Consulta SPC OK. Validar comprovante renda.",
    status: "em_andamento",
    prioridade: "alta",
    setor: "locacao",
    responsavelNome: "Renata Pacheco",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=26",
    prazo: "2026-05-23",
    criadaEm: yesterdayISO,
    atualizadaEm: todayISO,
    labels: ["aguardando_documento"],
    linkedTo: { tipo: "lead", id: "ld-007", titulo: "Bruno Carvalho" },
    origem: "manual",
  },
  {
    id: "tsk-loc-002",
    titulo: "Agendar entrega chaves — Patrícia Andrade",
    status: "aguardando_terceiros",
    prioridade: "normal",
    setor: "locacao",
    responsavelNome: "Renata Pacheco",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=26",
    prazo: "2026-05-26",
    criadaEm: dayBefore,
    atualizadaEm: yesterdayISO,
    labels: ["vistoria_agendar"],
    origem: "evento_sistema",
  },
  {
    id: "tsk-loc-003",
    titulo: "Reagendar visita — Lucas Ferreira",
    status: "a_fazer",
    prioridade: "normal",
    setor: "locacao",
    responsavelNome: "Renata Pacheco",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=26",
    prazo: "2026-05-24",
    criadaEm: yesterdayISO,
    atualizadaEm: yesterdayISO,
    labels: ["visita_confirmar"],
    origem: "ia",
  },

  // ============== CONCLUÍDAS (várias) ==============
  {
    id: "tsk-done-001",
    titulo: "Boleto emitido — Aluguel mai/2026 J. Tropical",
    status: "concluida",
    prioridade: "normal",
    setor: "financeiro",
    responsavelNome: "Marcelo Vieira",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=33",
    criadaEm: earlier,
    atualizadaEm: dayBefore,
    labels: ["boleto_emitir"],
    origem: "evento_sistema",
  },
  {
    id: "tsk-done-002",
    titulo: "LGPD: revogação consentimento — Pedro Alves",
    status: "concluida",
    prioridade: "normal",
    setor: "juridico",
    responsavelNome: "Bruno Tavares",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=12",
    criadaEm: earlier,
    atualizadaEm: dayBefore,
    labels: ["lgpd_processar"],
    origem: "evento_sistema",
  },
  {
    id: "tsk-done-003",
    titulo: "Visita confirmada — Apto Centro Bruno",
    status: "concluida",
    prioridade: "normal",
    setor: "captacao",
    responsavelNome: "Fernanda Pires",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=44",
    criadaEm: dayBefore,
    atualizadaEm: yesterdayISO,
    labels: ["visita_confirmar"],
    origem: "ia",
  },
  {
    id: "tsk-done-004",
    titulo: "Contrato vigente — Locação Apto Industrial",
    status: "concluida",
    prioridade: "normal",
    setor: "juridico",
    responsavelNome: "Dra. Patrícia Soares",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=47",
    criadaEm: earlier,
    atualizadaEm: dayBefore,
    labels: ["recolher_assinatura"],
    origem: "evento_sistema",
  },

  // ============== BLOQUEADAS ==============
  {
    id: "tsk-blk-001",
    titulo: "Renovação Industrial — aguardando aval gestor",
    descricao: "Locador pediu reajuste 18% (vs 7% IGPM). Decisão do gestor pendente.",
    status: "bloqueada",
    prioridade: "alta",
    setor: "juridico",
    responsavelNome: "Bruno Tavares",
    responsavelAvatarUrl: "https://i.pravatar.cc/150?img=12",
    criadaEm: earlier,
    atualizadaEm: yesterdayISO,
    labels: ["renovacao"],
    linkedTo: { tipo: "contrato", id: "ct-2023-008", titulo: "Locação Industrial" },
    origem: "evento_sistema",
    bloqueadaPor: "Decisão estratégica do gestor",
  },
];
